apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  labels:
    name: appc-service1
    namespace: crossplane-system
  name: appc-service1
spec:
  credentials:
    source: InjectedIdentity
